name: Build and test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'LICENSE'
    - 'README.md'
    - 'RELEASE_CHECKLIST.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_linux:
    name: Build and test on GNU/Linux
    runs-on: ubuntu-latest

    steps:
    - run: git config --global core.autocrlf false

    - name: "Checkout repository"
      uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --all --locked --verbose
    
    - name: Run tests
      run: cargo test --verbose

  build_and_test_macos:
    name: Build and test on macOS
    runs-on: macos-latest

    steps:
    - run: git config --global core.autocrlf false

    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --all --locked --verbose

    - name: Run tests
      run: cargo test --verbose

  build_and_test_windows:
    name: Build and test on Windows
    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf false

    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --all --locked --verbose

    - name: Run tests
      run: cargo test --verbose
